name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlite3 pandas
    - name: Apply Database Schema
      run: python scripts/db_creation.py
    - name: Import Data to Database
      run: python scripts/data_import.py
    - name: Perform Database Optimizations
      run: python scripts/optimization_analysis.py
    - name: Run Tests
      run: python -m unittest discover -s tests